import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";
import { LoadingPage } from "~/components/loading";
import { PageLayout } from "~/components/layout";
import { CreatePostWizard } from "~/components/createPostWizard";
import { Feed } from "~/components/feed";

export default function Home() {
  const { isSignedIn, isLoaded: userLoaded } = useUser();

  // Start fetching posts for feed
  api.posts.getAll.useQuery();

  // Return loading state if user is not loaded
  if (!userLoaded) return <LoadingPage size={64} />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <div className="flex border-b border-slate-400 p-4">
          {!isSignedIn && (
            <div className="flex justify-center">
              <SignInButton />
            </div>
          )}
          {isSignedIn && <CreatePostWizard />}
        </div>
        <Feed />
      </PageLayout>
    </>
  );
}
