import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import { type RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage } from "~/components/Loading";
import { useState } from "react";
import { set } from "zod";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user, isSignedIn } = useUser();
  const [content, setContent] = useState("");

  const ctx = api.useContext();

  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: async () => {
      setContent("");
      await ctx.posts.getAll.invalidate();
    },
  });

  if (!isSignedIn) return null;

  return (
    <div className="flex w-full gap-3">
      <Image
        src={user.profileImageUrl}
        alt={user.fullName ?? ""}
        width={56}
        height={56}
        className="h-14 w-14 rounded-full"
      />
      <input
        placeholder="Type some emojis!"
        className="grow bg-transparent outline-none"
        type="text"
        value={content}
        disabled={isPosting}
        onChange={(e) => setContent(e.target.value)}
        onKeyUp={(e) => {
          if (e.key !== "Enter") return;
          mutate({ content });
        }}
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = ({ post, author }: PostWithUser) => {
  const timeSince = dayjs(post.createdAt).fromNow();

  return (
    <div key={post.id} className="flex gap-3 border-b border-slate-400 p-4">
      <Image
        src={author.profileImageUrl}
        alt={author.username ?? ""}
        width={48}
        height={48}
        className="h-12 w-12 rounded-full"
      />
      <div className="flex flex-col">
        <div className="flex gap-2 font-bold text-slate-300">
          <span>{`@${author.username} `}</span>
          <span>{" · "}</span>
          <span className="font-thin">{`${timeSince}`}</span>
        </div>
        <div className="text-2xl">{post.content}</div>
      </div>
    </div>
  );
};

const Feed = () => {
  const { isLoaded: userLoaded } = useUser();

  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  // Return empty div if user and posts are not loaded
  if (!userLoaded && postsLoading) return <div />;

  if (!data) return <div>Something went wrong</div>;

  if (!userLoaded) return <LoadingPage size={64} />;

  return (
    <div className="flex flex-col">
      {data?.map((fullPost) => (
        <PostView key={fullPost.post.id} {...fullPost} />
      ))}
    </div>
  );
};

export default function Home() {
  const { isSignedIn, isLoaded: userLoaded } = useUser();

  // Start fetching posts
  api.posts.getAll.useQuery();

  // Return empty div if user is not loaded
  if (!userLoaded) return <LoadingPage size={64} />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {isSignedIn && <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
}
